services:
    app:
        build: .
        container_name: EscapeAll-Notifier
        restart: always
        volumes:
            - .:/var/www/html
            - /var/www/html/vendor
            - /var/www/html/node_modules
            - playwright_cache:/root/.cache/ms-playwright

        ports:
            - "8000:8000"
        depends_on:
            - db
        environment:
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: EscapeAll-Notifier-db
            DB_USERNAME: Escaper
            DB_PASSWORD: apedrasant

    db:
        image: mysql:8.0
        container_name: EscapeAll-Notifier-db
        restart: always
        environment:
            MYSQL_DATABASE: EscapeAll-Notifier-db
            MYSQL_USER: Escaper
            MYSQL_PASSWORD: apedrasant
            MYSQL_ROOT_PASSWORD: apedrasant
        ports:
            - "3309:3306"
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
    playwright_cache:
